### ISSUE TITLE
MolecularGraph

### ISSUE THREAD

**Issue by timholy** [aced-differentiate/ChemistryFeaturization.jl#34]
I came here from https://julialang.org/jsoc/gsoc/deepchem/ which looks really exciting.

Just to make sure efforts are as non-redundant as possible...I may have chatted with @rkurchin previously about this, but I can't find an issue. Since you mention SMILES and other such stuff, are you aware of:
- https://github.com/mojaie/MolecularGraph.jl (this package is less discoverable than it deserves, I'm not sure why but see https://github.com/JuliaComputing/JuliaHub/issues/81)
- https://github.com/JuliaHealth/PubChemCrawler.jl

**Comment by rkurchin** [comment]
Thanks! I was actually aware of the first but not the second. At the moment my personal efforts are focused on bulk systems, so the molecular side is more in the "nice to have" category, but these are definitely both great to keep in mind if/when focus shifts/expands!

**Comment by DhairyaLGandhi** [comment]
There's also OpenSMILES.jl

**Comment by timholy** [comment]
Yes, it's effectively subsumed. https://github.com/caseykneale/OpenSMILES.jl#notice

(It's author and I have talked extensively.)
