### ISSUE TITLE
add "overwrite" option in build_graphs_batch

### ISSUE THREAD

**Issue by rkurchin** [aced-differentiate/ChemistryFeaturization.jl#45]
Should default to true, but if false checks if given path already exists in output folder and skips to speed things up, allow finishing an interrupted graph-building

**Comment by thazhemadam** [comment]
If it skips to speed things up, wouldn't models using this be relatively faster if this were to default to `false` instead?

**Comment by rkurchin** [comment]
hahaha yes I did say that backwards, good catch...OBO errors are a real bitch in binary, eh? 😆
